In [2]:
import pandas as pd

dfs = [
    'final_jobs.csv',
    'final_people.csv',
    'final_organizations.csv',
    'final_qualifications.csv',
    'final_courses_and_programs.csv',
    'final_skills.csv'
]
parent_folder = ['final_dataset_courseprograms_joined']
# print columns
for df in dfs:
    print(df)
    df = pd.read_csv(parent_folder[0] + '/' + df)
    print(df.columns)



final_jobs.csv
Index(['TITLE', 'O*NET-SOC Code', 'ID'], dtype='object')
final_people.csv
Index(['EMP_TYP_ID', 'IS_ACTIVE_INFERRED', 'FULLTIME', 'DMN_ID', 'HIRE_DTE',
       'STUD_ID'],
      dtype='object')
final_organizations.csv
Index(['ORG_ID'], dtype='object')
final_qualifications.csv
Index(['NOTACTIVE', 'CREATE_DTE', 'QUAL_TYP_ID', 'DMN_ID', 'TITLE',
       'TITLE_TRANSLATION_NEEDED', 'DESC_TRANSLATION_NEEDED', 'DESCRIPTION',
       'REAL_ID', 'LEARNING_ITEM_ID', 'QUAL_ID'],
      dtype='object')
final_courses_and_programs.csv
Index(['NOTACTIVE', 'REV_DTE', 'CREATE_DTE', 'TOTAL_RATING', 'AVG_RATING',
       'CPNT_CLASSIFICATION', 'CPNT_TYP_ID', 'DMN_ID', 'CPNT_SRC_ID',
       'CREDIT_HRS', 'THUMBNAIL_URI', 'TITLE', 'TITLE_TRANSLATION_NEEDED',
       'DESC_TRANSLATION_NEEDED', 'DESCRIPTION', 'LEARNING_TYPE', 'REAL_ID',
       'LEARNING_ITEM_ID'],
      dtype='object')
final_skills.csv
Index(['SKILL'], dtype='object')


In [36]:
df = pd.DataFrame(data=[[[1,2,3],12,13], [[1,2,3],14,15]], columns = ['a','b','c'])
df

a   b   c
0  [1, 2, 3]  12  13
1  [1, 2, 3]  14  15

In [ ]:
# numpy remove dimensions
import numpy as np
a = np.array([[[1,2,3],[1,2,3]]])
a.shape
a = a.squeeze()


In [16]:
import torch
torch.from_numpy(df.to_numpy().tolist())

TypeError: expected np.ndarray (got list)

In [43]:
tensor_obj = None
for col in df.columns:
    if type(df[col].values[0]) == np.ndarray or type(df[col].values[0]) == list:
        temp_obj = torch.tensor(df[col].to_numpy().tolist())
    else:
        temp_obj = torch.tensor(df[col].values).reshape(-1,1)
        
    if tensor_obj is None:
        tensor_obj = temp_obj
    else:
        tensor_obj = torch.cat((tensor_obj, temp_obj), dim=1)

tensor_obj

tensor([[12],
        [14]]) a tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([[13],
        [15]]) a tensor([[ 1,  2,  3, 12],
        [ 1,  2,  3, 14]])


tensor([[ 1,  2,  3, 12, 13],
        [ 1,  2,  3, 14, 15]])

In [20]:
import numpy as np 
np.array(df.to_numpy().tolist())

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.