In [44]:
from torch_geometric.utils import to_undirected
from torch_sparse import SparseTensor

def undirected_triangle_count(edge_index, max_num_nodes ):
    ud = to_undirected(edge_index)
    adj_matrix = SparseTensor(row=ud[0], col=ud[1], sparse_sizes=(max_num_nodes, max_num_nodes))
    
    adj_matrix.matmul(adj_matrix.matmul(adj_matrix))

In [2]:


import torch

# Example tensor E (replace this with your actual tensor)
E = torch.tensor([[1, 0, 1],
                  [0, 1, 0],
                  [1, 0, 0]])

# Example matrices A and B (replace these with your actual matrices)
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

B = torch.tensor([[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]])

# Indices of non-zero elements of E
indices_i, indices_j = E.nonzero().unbind(dim=1)

# Select rows of A and columns of B using the indices from E
A = A[indices_i]
B = B[:, indices_j]

# Calculate the values of C
C = torch.sum(A * B.transpose(0, 1), dim=1)

In [10]:
E.nonzero()

tensor([[0, 0],
        [0, 2],
        [1, 1],
        [2, 0]])

In [6]:
indices_i

tensor([0, 0, 1, 2])

In [5]:
B

tensor([[10, 12, 11, 10],
        [13, 15, 14, 13],
        [16, 18, 17, 16]])

In [4]:
B.transpose(0, 1)

tensor([[10, 13, 16],
        [12, 15, 18],
        [11, 14, 17],
        [10, 13, 16]])

In [3]:
C


tensor([ 84,  96, 216, 318])

In [107]:
import torch

# Define the range of numbers from 1 to X
X = 303483  # Replace with your desired maximum value

# Define the number of columns (N) in the 2xN tensor
N = 1574932  # Replace with your desired number of columns

# Create a random 2xN tensor with numbers from 1 to X
random_tensor = torch.randint(0, X , (2, N))

print(random_tensor)

tensor([[120785, 102679, 293561,  ..., 233174,  17795, 299874],
        [204468, 254401, 169163,  ..., 244653,  92271, 189677]])


In [10]:
undirected_triangle_count(random_tensor, X)

In [ ]:
masked_select

In [49]:
adj_matrix = SparseTensor(row=torch.tensor([0,1,2,3,4,5,6,7,8,9,10]), col=torch.tensor([0,1,2,3,4,5,6,7,8,9,10]), sparse_sizes=(11,11), value=torch.Tensor([1,2,3,4,5,6,7,8,9,10,11]))

In [50]:
adj_matrix.to_dense()

tensor([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 11.]])

In [67]:
from torch_sparse.masked_select import masked_select

masked_select(adj_matrix, dim=-1, mask=torch.tensor([[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[0]])).to_dense()

AssertionError: 

In [108]:

ud = to_undirected(random_tensor)
adj_matrix = SparseTensor(row=ud[0], col=ud[1], sparse_sizes=(X, X))

In [80]:
adj_matrix[:4].to_dense().shape

torch.Size([4, 303483])

303483

In [103]:

adj_matrix = SparseTensor(row=torch.tensor([0,1,2,3,4,5,6,7,8,9,10]), col=torch.tensor([0,1,2,3,4,5,6,7,8,9,10]), sparse_sizes=(11,11), value=torch.Tensor([1,2,3,4,5,6,7,8,9,10,11]))

get_diag(adj_matrix)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [133]:
from torch_sparse import from_torch_sparse, to_torch_sparse

In [143]:
from torch_geometric.utils.sparse import dense_to_sparse, to_torch_sparse_tensor
graph = torch.Tensor([[0, 1, 1, 0],
         [1, 0, 1, 1],
         [1, 1, 0, 1],
         [0, 1, 1, 0]])

s = SparseTensor.from_dense(graph)
print(s)

x = blockwise_sparse_square_mmul( s)
x = blockwise_sparse_square_mmul( s, x)
blockwise_sparse_get_diag(x)

SparseTensor(row=tensor([0, 0, 1, 1, 1, 2, 2, 2, 3, 3]),
             col=tensor([1, 2, 0, 2, 3, 0, 1, 3, 1, 2]),
             val=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
             size=(4, 4), nnz=10, density=62.50%)


get blockwise sparse matrix diagonal: 100%|██████████| 1/1 [00:00<00:00, 1662.43it/s]


tensor([2., 4., 4., 2.])

In [142]:
SparseTensor.from_dense(graph).spspmm(SparseTensor.from_dense(graph))

RuntimeError: "sparse_matmul" not implemented for 'Long'

In [130]:
SparseTensor(

SyntaxError: incomplete input (2370253991.py, line 1)

In [119]:
blockwise_sparse_get_diag(a)

get blockwise sparse matrix diagonal: 100%|██████████| 31/31 [00:00<00:00, 400.65it/s]


tensor([1., 1., 1.,  ..., 0., 0., 0.])

In [88]:
result

SparseTensor(row=tensor([     0,      0,      0,  ..., 303482, 303482, 303482]),
             col=tensor([     0,   4506,   9851,  ..., 287480, 299152, 303482]),
             size=(303483, 303483), nnz=32997613, density=0.04%)

In [13]:
type(adj_matrix)

torch_sparse.tensor.SparseTensor

In [17]:
adj_matrix

AttributeError: 'SparseTensor' object has no attribute 'index'

In [40]:
%time adj_matrix.spspmm(adj_matrix.spspmm(adj_matrix))


CPU times: user 3.63 s, sys: 63.6 ms, total: 3.69 s
Wall time: 2.92 s


SparseTensor(row=tensor([     0,      0,      0,  ..., 999999, 999999, 999999]),
             col=tensor([ 22733, 118365, 136800,  ..., 442477, 784702, 863399]),
             size=(1000000, 1000000), nnz=10009131, density=0.00%)

In [41]:
%time adj_matrix.matmul(adj_matrix.matmul(adj_matrix))

CPU times: user 3.78 s, sys: 86.7 ms, total: 3.87 s
Wall time: 3.04 s


SparseTensor(row=tensor([     0,      0,      0,  ..., 999999, 999999, 999999]),
             col=tensor([ 22733, 118365, 136800,  ..., 442477, 784702, 863399]),
             size=(1000000, 1000000), nnz=10009131, density=0.00%)

In [ ]:
masked_select

In [18]:
from torch_sparse import eye, masked_select, spspmm

spspmm(adj_matrix,adj_matrix)


TypeError: spspmm() missing 5 required positional arguments: 'indexB', 'valueB', 'm', 'k', and 'n'